{{- if and .Values.controller.enabled .Values.serviceAccount.controller.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prepuller.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prepuller.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
  {{- with .Values.serviceAccount.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if and .Values.agent.enabled .Values.serviceAccount.agent.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prepuller.agentServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prepuller.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-agent
  {{- with .Values.serviceAccount.agent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
