apiVersion: apps/v1
kind: Deployment
metadata:
  name: prepuller-controller-manager
  labels:
    app.kubernetes.io/name: prepuller
    app.kubernetes.io/component: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prepuller
      app.kubernetes.io/component: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prepuller
        app.kubernetes.io/component: controller-manager
    spec:
      serviceAccountName: prepuller-controller-manager
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        image: controller:latest
        imagePullPolicy: IfNotPresent
        args:
        - --leader-elect
        # Set to a comma-separated list such as "linux/amd64,linux/arm64" to limit resolved platforms.
        # - --platforms=linux/amd64,linux/arm64
        command:
        - /manager
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
