apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prepuller-agent-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - prepuller.theatreofdreams.dev
  resources:
  - images
  verbs:
  - get
  - list
  - watch
